### ISSUE TITLE
microg downloads 404

### ISSUE THREAD

**Issue by noideaman** [SinTan1729/ReVancedBuilder#2]
Looks like the microg assets have changed, they dont go by microg any more but 

For all devices
 app.revanced.android.gms-(string involving version)-signed.apk 

For Huawei and Xiaomi
 app.revanced.android.gms-(string involving version)-hw-signed.apk 
 
 Otherwise the builder fails to download

**Comment by SinTan1729** [comment]
@noideaman Thank you for reporting. I pushed a commit to address this. If this doesn't fix it for you, feel free to reopen the issue.
